from django.urls import include, path, re_path
from django.views.generic import RedirectView
from . import views
urlpatterns = [
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("startups/", views.startups_list, name="startups_list"),
    # Startup category SEO pages
    path("startups/tehnologii/", views.startups_by_category, {"category_slug": "tehnologii"}, name="startups_cat_tehnologii"),
    path("startups/finansy/", views.startups_by_category, {"category_slug": "finansy"}, name="startups_cat_finansy"),
    path("startups/obrazovanie/", views.startups_by_category, {"category_slug": "obrazovanie"}, name="startups_cat_obrazovanie"),
    path("startups/ai/", views.startups_by_category, {"category_slug": "ai"}, name="startups_cat_ai"),
    path("startups/zdorove/", views.startups_by_category, {"category_slug": "zdorove"}, name="startups_cat_zdorove"),
    path("startups/eda/", views.startups_by_category, {"category_slug": "eda"}, name="startups_cat_eda"),
    path("startups/ekologiya/", views.startups_by_category, {"category_slug": "ekologiya"}, name="startups_cat_ekologiya"),
    path("startups/sport/", views.startups_by_category, {"category_slug": "sport"}, name="startups_cat_sport"),
    # Startup funding range SEO pages
    path("startups/do-1m/", views.startups_by_funding, {"range_slug": "do-1m"}, name="startups_fund_do_1m"),
    path("startups/do-5m/", views.startups_by_funding, {"range_slug": "do-5m"}, name="startups_fund_do_5m"),
    path("startups/ot-5m-do-20m/", views.startups_by_funding, {"range_slug": "ot-5m-do-20m"}, name="startups_fund_5m_20m"),
    path("startups/ot-20m/", views.startups_by_funding, {"range_slug": "ot-20m"}, name="startups_fund_ot_20m"),
    path("startups/<slug:slug>/", views.startup_detail, name="startup_detail"),
    path("startups/id/<int:startup_id>/", views.startup_detail_by_id, name="startup_detail_by_id"),
    path("franchises/", views.franchises_list, name="franchises_list"),
    path("franchise-landing/", views.franchise_landing, name="franchise_landing"),
    path("franchise-cards-test/", views.franchise_cards_test, name="franchise_cards_test"),
    path("franchise-detail-test/<slug:slug>/", views.franchise_detail_test, name="franchise_detail_test"),
    path("franchise-landing-b/", views.franchise_landing_b, name="franchise_landing_b"),
    path("franchise-landing-c/", views.franchise_landing_c, name="franchise_landing_c"),
    path("franchise-landing-d/", views.franchise_landing_d, name="franchise_landing_d"),
    path("franchises/city/<slug:city_slug>/", views.franchises_by_city, name="franchises_by_city"),
    path("franchises/beauty/", views.franchises_by_direction, {"direction_slug": "beauty"}, name="franchises_dir_beauty"),
    path("franchises/kafe-restorany/", views.franchises_by_direction, {"direction_slug": "kafe-restorany"}, name="franchises_dir_cafe"),
    path("franchises/dostavka/", views.franchises_by_direction, {"direction_slug": "dostavka"}, name="franchises_dir_delivery"),
    path("franchises/fastfud/", views.franchises_by_direction, {"direction_slug": "fastfud"}, name="franchises_dir_fastfood"),
    path("franchises/finansy/", views.franchises_by_direction, {"direction_slug": "finansy"}, name="franchises_dir_finance"),
    path("franchises/zdorove/", views.franchises_by_direction, {"direction_slug": "zdorove"}, name="franchises_dir_healthcare"),
    path("franchises/sport/", views.franchises_by_direction, {"direction_slug": "sport"}, name="franchises_dir_sport"),
    path("franchises/tekhnologii/", views.franchises_by_direction, {"direction_slug": "tekhnologii"}, name="franchises_dir_tech"),
    # 301 redirects from old /direction/ URLs
    path("franchises/direction/<slug:direction_slug>/", views.franchises_by_direction_redirect, name="franchises_by_direction_old"),
    path("franchises/direction/<int:direction_id>/", views.franchises_by_direction_legacy, name="franchises_by_direction_legacy"),
    path("franchises/do-500k/", views.franchises_by_investment, {"range_slug": "do-500k"}, name="franchises_by_investment_500k"),
    path("franchises/do-1m/", views.franchises_by_investment, {"range_slug": "do-1m"}, name="franchises_by_investment_1m"),
    path("franchises/ot-1m-do-5m/", views.franchises_by_investment, {"range_slug": "ot-1m-do-5m"}, name="franchises_by_investment_1m5m"),
    path("franchises/ot-5m/", views.franchises_by_investment, {"range_slug": "ot-5m"}, name="franchises_by_investment_5m"),
    path("franchises/<slug:slug>/", views.franchise_detail, name="franchise_detail"),
    path("franchises/id/<int:franchise_id>/", views.franchise_detail_by_id, name="franchise_detail_by_id"),
    path("agencies/", views.agencies_list, name="agencies_list"),
    # Agency category SEO pages
    path("agencies/web-razrabotka/", views.agencies_by_category, {"category_slug": "web-razrabotka"}, name="agencies_cat_web"),
    path("agencies/mobilnaya-razrabotka/", views.agencies_by_category, {"category_slug": "mobilnaya-razrabotka"}, name="agencies_cat_mobile"),
    path("agencies/dizajn/", views.agencies_by_category, {"category_slug": "dizajn"}, name="agencies_cat_design"),
    path("agencies/marketing/", views.agencies_by_category, {"category_slug": "marketing"}, name="agencies_cat_marketing"),
    path("agencies/ai/", views.agencies_by_category, {"category_slug": "ai"}, name="agencies_cat_ai"),
    path("agencies/brending/", views.agencies_by_category, {"category_slug": "brending"}, name="agencies_cat_branding"),
    path("agencies/video/", views.agencies_by_category, {"category_slug": "video"}, name="agencies_cat_video"),
    path("agencies/perevod/", views.agencies_by_category, {"category_slug": "perevod"}, name="agencies_cat_translation"),
    path("agencies/<slug:slug>/", views.agency_detail, name="agency_detail"),
    path("agencies/id/<int:agency_id>/", views.agency_detail_by_id, name="agency_detail_by_id"),
    path("vote-agency/<int:agency_id>/", views.vote_agency, name="vote_agency"),
    path("specialists/", views.specialists_list, name="specialists_list"),
    # Specialist category SEO pages
    path("specialists/web-razrabotka/", views.specialists_by_category, {"category_slug": "web-razrabotka"}, name="specialists_cat_web"),
    path("specialists/mobilnaya-razrabotka/", views.specialists_by_category, {"category_slug": "mobilnaya-razrabotka"}, name="specialists_cat_mobile"),
    path("specialists/dizajn/", views.specialists_by_category, {"category_slug": "dizajn"}, name="specialists_cat_design"),
    path("specialists/marketing/", views.specialists_by_category, {"category_slug": "marketing"}, name="specialists_cat_marketing"),
    path("specialists/ai/", views.specialists_by_category, {"category_slug": "ai"}, name="specialists_cat_ai"),
    path("specialists/brending/", views.specialists_by_category, {"category_slug": "brending"}, name="specialists_cat_branding"),
    path("specialists/video/", views.specialists_by_category, {"category_slug": "video"}, name="specialists_cat_video"),
    path("specialists/perevod/", views.specialists_by_category, {"category_slug": "perevod"}, name="specialists_cat_translation"),
    path("specialists/<slug:slug>/", views.specialist_detail, name="specialist_detail"),
    path("specialists/id/<int:specialist_id>/", views.specialist_detail_by_id, name="specialist_detail_by_id"),
    path("vote-specialist/<int:specialist_id>/", views.vote_specialist, name="vote_specialist"),
    path("edit-franchise/<int:franchise_id>/", views.edit_franchise, name="edit_franchise"),
    path("edit-agency/<int:agency_id>/", views.edit_agency, name="edit_agency"),
    path("edit-specialist/<int:specialist_id>/", views.edit_specialist, name="edit_specialist"),
    path("approve-franchise/<int:franchise_id>/", views.approve_franchise, name="approve_franchise"),
    path("reject-franchise/<int:franchise_id>/", views.reject_franchise, name="reject_franchise"),
    path("approve-agency/<int:agency_id>/", views.approve_agency, name="approve_agency"),
    path("reject-agency/<int:agency_id>/", views.reject_agency, name="reject_agency"),
    path("approve-specialist/<int:specialist_id>/", views.approve_specialist, name="approve_specialist"),
    path("reject-specialist/<int:specialist_id>/", views.reject_specialist, name="reject_specialist"),
    path("vote-franchise/<int:franchise_id>/", views.vote_franchise, name="vote_franchise"),
    path("load_similar_franchises/<int:franchise_id>/", views.load_similar_franchises, name="load_similar_franchises"),
    path("load_similar_agencies/<int:agency_id>/", views.load_similar_agencies, name="load_similar_agencies"),
    path("load_similar_specialists/<int:specialist_id>/", views.load_similar_specialists, name="load_similar_specialists"),
    path("change_owner/<int:startup_id>/", views.change_owner, name="change_owner"),
    path("get_investors/<int:startup_id>/", views.get_investors, name="get_investors"),
    path("add_investor/<int:startup_id>/", views.add_investor, name="add_investor"),
    path(
        "edit_investment/<int:startup_id>/<int:user_id>/",
        views.edit_investment,
        name="edit_investment",
    ),
    path(
        "delete_investment/<int:startup_id>/<int:user_id>/",
        views.delete_investment,
        name="delete_investment",
    ),
    path("change_owner_franchise/<int:franchise_id>/", views.change_owner_franchise, name="change_owner_franchise"),
    path("change_owner_agency/<int:agency_id>/", views.change_owner_agency, name="change_owner_agency"),
    path("change_owner_specialist/<int:specialist_id>/", views.change_owner_specialist, name="change_owner_specialist"),
    path("get_investors_franchise/<int:franchise_id>/", views.get_investors_franchise, name="get_investors_franchise"),
    path("add_investor_franchise/<int:franchise_id>/", views.add_investor_franchise, name="add_investor_franchise"),
    path("edit_investment_franchise/<int:franchise_id>/<int:user_id>/", views.edit_investment_franchise, name="edit_investment_franchise"),
    path("delete_investment_franchise/<int:franchise_id>/<int:user_id>/", views.delete_investment_franchise, name="delete_investment_franchise"),
    path("investments/", views.investments, name="investments"),
    # Blog (formerly News)
    path("blog/", views.news, name="news"),
    path("blog/suggest/", views.suggest_news, name="suggest_news"),
    path("api/news/similar/", views.api_similar_news, name="api_similar_news"),
    re_path(r"^blog/(?P<slug>[-\w]+)/$", views.news_detail, name="news_detail"),
    re_path(r"^blog/(?P<slug>[-\w]+)/edit/$", views.edit_news, name="edit_news"),
    re_path(r"^blog/(?P<slug>[-\w]+)/delete/$", views.delete_news, name="delete_news"),
    path("blog/comment/<int:comment_id>/delete/", views.delete_news_comment, name="delete_news_comment"),
    # Redirects from old /news/ URLs
    path("news/", RedirectView.as_view(url="/blog/", permanent=True)),
    path("news/suggest/", RedirectView.as_view(url="/blog/suggest/", permanent=True)),
    re_path(r"^news/(?P<slug>[-\w]+)/$", lambda r, slug: redirect(f"/blog/{slug}/", permanent=True)),
    path("cosmochat/", views.cosmochat, name="cosmochat"),
    path("cosmochat/chat-list/", views.chat_list, name="chat_list"),
    path("cosmochat/<int:chat_id>/", views.get_chat_messages, name="get_chat_messages"),
    path("cosmochat/send-message/", views.send_message, name="send_message"),
    path(
        "cosmochat/mark-read/<int:chat_id>/",
        views.mark_messages_read,
        name="mark_messages_read",
    ),
    path("cosmochat/start-chat/<int:user_id>/", views.start_chat, name="start_chat"),
    path(
        "cosmochat/add-participant/<int:chat_id>/",
        views.add_participant,
        name="add_participant",
    ),
    path("cosmochat/leave-chat/<int:chat_id>/", views.leave_chat, name="leave_chat"),
    path(
        "cosmochat/create-group-chat/",
        views.create_group_chat,
        name="create_group_chat",
    ),
    path(
        "cosmochat/available-users-for-chat/<int:chat_id>/",
        views.available_users_for_chat,
        name="available_users_for_chat",
    ),
    path("cosmochat/rename-chat/<int:chat_id>/", views.rename_chat, name="rename_chat"),
    path("cosmochat/available_users/", views.available_users, name="available_users"),
    path("cosmochat/start-deal/<int:chat_id>/", views.start_deal, name="start_deal"),
    path("profile/", views.profile, name="profile"),
    path("profile/delete-avatar/", views.delete_avatar, name="delete_avatar"),
    path("profile/<int:user_id>/", views.profile, name="user_profile"),
    path("create-startup/", views.create_startup, name="create_startup"),
    path("create-franchise/", views.create_franchise, name="create_franchise"),
    path("create-agency/", views.create_agency, name="create_agency"),
    path("create-specialist/", views.create_specialist, name="create_specialist"),
    path(
        "create-startup/success/",
        views.startup_creation_success,
        name="startup_creation_success",
    ),
    path(
        "create-agency/success/",
        views.agency_creation_success,
        name="agency_creation_success",
    ),
    path(
        "create-franchise/success/",
        views.franchise_creation_success,
        name="franchise_creation_success",
    ),
    path(
        "create-specialist/success/",
        views.specialist_creation_success,
        name="specialist_creation_success",
    ),
    path("edit-startup/<int:startup_id>/", views.edit_startup, name="edit_startup"),
    path("moderator-main/", views.main_page_moderator, name="main_page_moderator"),
    path("investor-main/", views.investor_main, name="investor_main"),
    path("startuper-main/", views.startuper_main, name="startuper_main"),
    path("moderator-dashboard/", views.moderator_dashboard, name="moderator_dashboard"),
    path(
        "approve-startup/<int:startup_id>/",
        views.approve_startup,
        name="approve_startup",
    ),
    path(
        "reject-startup/<int:startup_id>/", views.reject_startup, name="reject_startup"
    ),
    path("vote-startup/<int:startup_id>/", views.vote_startup, name="vote_startup"),
    path("invest/<int:startup_id>/", views.invest, name="invest"),
    path("invest-franchise/<int:franchise_id>/", views.invest_franchise, name="invest_franchise"),
    # AI Franchise Import (moderator only)
    path("import-franchise/", views.franchise_import, name="franchise_import"),
    # Franchisee Discovery
    path("moderator/franchisee-discovery/", views.franchisee_discovery_list, name="franchisee_discovery_list"),
    path("moderator/franchisee-discovery/analyze/<int:franchise_id>/", views.analyze_franchise_contacts, name="analyze_franchise_contacts"),
    path("moderator/franchisee-discovery/<int:franchise_id>/contacts/", views.franchisee_contacts_detail, name="franchisee_contacts_detail"),
    path("moderator/franchisee-discovery/contact/<int:contact_id>/update/", views.update_franchisee_contact, name="update_franchisee_contact"),
    path("moderator/franchisee-discovery/contact/<int:contact_id>/deep-research/", views.deep_research_contact, name="deep_research_contact"),
    path("moderator/franchisee-discovery/<int:franchise_id>/deep-research-all/", views.deep_research_all, name="deep_research_all"),
    path("moderator/franchisee-discovery/status/<int:log_id>/", views.franchisee_analysis_status, name="franchisee_analysis_status"),
    # Lead Generation
    path("leads/create/", views.create_lead, name="create_lead"),
    path("my-leads/", RedirectView.as_view(pattern_name="my_analytics", permanent=False), name="my_leads"),
    path("leads/<int:lead_id>/update-status/", views.update_lead_status, name="update_lead_status"),
    path("leads/export/", views.export_leads, name="export_leads"),
    path("settings/crm/", views.crm_settings, name="crm_settings"),
    path("edit-ai-rating/<str:entity_type>/<int:entity_id>/", views.edit_ai_rating, name="edit_ai_rating"),
    path("search-suggestions/", views.search_suggestions, name="search_suggestions"),
    path("global-search/", views.global_search, name="global_search"),
    path("planetary-system/", views.planetary_system, name="planetary_system"),
    path("my_startups/", views.my_startups, name="my_startups"),
    path("my_startups/download-report/", views.download_startups_report, name="download_startups_report"),
    path(
        "load_similar_startups/<int:startup_id>/",
        views.load_similar_startups,
        name="load_similar_startups",
    ),
    path("deals/", views.deals_view, name="deals_view"),
    path("deals/approve/<int:chat_id>/", views.approve_deal, name="approve_deal"),
    path("deals/reject/<int:chat_id>/", views.reject_deal, name="reject_deal"),
    path("notifications/", views.notifications_view, name="notifications_page"),
    path("support/", views.support_page_view, name="support"),
    path("support/orders/", views.support_orders_view, name="support_orders"),
    path(
        "support/ticket/<int:ticket_id>/",
        views.support_ticket_detail,
        name="support_ticket_detail",
    ),
    path(
        "support/ticket/<int:ticket_id>/close/",
        views.close_support_ticket,
        name="close_support_ticket",
    ),
    path(
        "support/ticket/<int:ticket_id>/update-status/",
        views.update_ticket_status,
        name="update_ticket_status",
    ),
    path("support/contact/", views.support_contact_view, name="support_contact"),
    path(
        "telegram-bot-webhook/<str:token>/",
        views.telegram_webhook,
        name="telegram_webhook",
    ),
    path(
        "favicon.ico",
        RedirectView.as_view(url="/static/images/favicon.png", permanent=True),
    ),
    path("faq/", views.faq_page_view, name="faq"),
    path("contacts/", views.contacts_page_view, name="contacts"),
    path("legal/", views.legal, name="legal"),
    path(
        "chats/find_or_create/<int:recipient_id>/",
        views.find_or_create_chat,
        name="find_or_create_chat",
    ),
    path(
        "delete-message/<int:message_id>/", views.delete_message, name="delete_message"
    ),
    path("delete-comment/startup/<int:comment_id>/", views.delete_startup_comment, name="delete_startup_comment"),
    path("delete-comment/franchise/<int:comment_id>/", views.delete_franchise_comment, name="delete_franchise_comment"),
    path("delete-comment/agency/<int:comment_id>/", views.delete_agency_comment, name="delete_agency_comment"),
    path("delete-comment/specialist/<int:comment_id>/", views.delete_specialist_comment, name="delete_specialist_comment"),
    path("reorder-files/<str:entity_type>/<int:entity_id>/", views.reorder_files, name="reorder_files"),
    path("delete-file/<str:entity_type>/<int:entity_id>/", views.delete_file, name="delete_file"),
    path(
        "remove-participant/<int:chat_id>/",
        views.remove_participant,
        name="remove_participant",
    ),
    path(
        "cosmochat/<int:chat_id>/messages/",
        views.get_chat_messages,
        name="get_chat_messages_dynamic",
    ),
    path("api/ckeditor-upload/", views.ckeditor_upload, name="ckeditor_upload"),
    path("upload-description-media/<str:entity_type>/<int:entity_id>/", views.upload_description_media, name="upload_description_media"),
    path("get-description-media/<str:entity_type>/<int:entity_id>/", views.get_description_media, name="get_description_media"),
    path("delete-description-media/<str:entity_type>/<int:entity_id>/<str:file_id>/", views.delete_description_media, name="delete_description_media"),
    # Временная загрузка файлов при создании сущности
    path("temp-upload/", views.temp_file_upload, name="temp_file_upload"),
    path("temp-files/", views.get_temp_files, name="get_temp_files"),
    path("temp-delete/<str:temp_id>/", views.delete_temp_file, name="delete_temp_file"),
    path("my-analytics/", views.my_analytics, name="my_analytics"),
    path("api/track/pageview/", views.track_page_view, name="track_page_view"),
    path("api/track/click/", views.track_click, name="track_click"),
    path("api/track/impression/", views.track_impression, name="track_impression"),
    path("api/track/engagement/", views.track_engagement, name="track_engagement"),
]
