[providers]
python = 'python311'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.setup]
nixPkgs = ['python311', 'nodejs_18', 'npm-9_x', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --break-system-packages -r requirements.txt', 'npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'gunicorn --bind 0.0.0.0:8000 marketplace.wsgi:application'