[phases.setup]
nixPkgs = ['python311', 'nodejs_18', 'npm-9_x', 'python311Packages.pip']

[phases.install]
cmds = ['python -m pip install --break-system-packages -r requirements.txt', 'npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && gunicorn --bind 0.0.0.0:3000 marketplace.wsgi:application'