[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'nodejs_20']

[phases.install]
cmds = [
    'pip install --break-system-packages -r requirements.txt',
    'npm install'
]

[phases.build]
cmds = ['npm run build']

[variables]
PATH = '/opt/venv/bin:$PATH'

[start]
cmd = 'python manage.py collectstatic --noinput --clear && python -m gunicorn --bind 0.0.0.0:3000 marketplace.wsgi:application'
