[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip install --break-system-packages -r requirements.txt']

[variables]
PATH = '/opt/venv/bin:$PATH'

[start]
cmd = 'python manage.py collectstatic --noinput --clear && which gunicorn && ls -la /opt/venv/bin/gunicorn && /opt/venv/bin/gunicorn --bind 0.0.0.0:3000 marketplace.wsgi:application'
