[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "staticfiles",
    "node_modules",
    "accounts/templates",
    "marketplace/templates",
    "static/src",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C4", # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = ["E501"] # ignore line length errors, handled by the formatter

[tool.ruff.lint.isort]
known-first-party = ["accounts", "marketplace"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.per-file-ignores]
"manage.py" = ["E402"]
"settings.py" = ["E402"]
"**/migrations/*.py" = ["E501"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "marketplace.settings"
