[tool.ruff]
line-length = 88
extend-exclude = [
    "node_modules",
    "venv",
    ".venv",
    "static",
    "staticfiles",
    "accounts/templates",
    "marketplace/templates",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "C4", "B"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "marketplace.settings"
