# Generated by Django 4.2.13 on 2025-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_update_telegram_social_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='specialist_id',
            field=models.AutoField(db_column='startup_id', primary_key=True, serialize=False),
        ),
    ]
