# Generated by Django 4.2.13 on 2025-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_fix_agencies_specialists_db_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencies',
            name='agency_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
