# Generated by Django 4.2.13 on 2025-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_fix_agencies_db_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='specialist_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
