# Generated by Django - merge migration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_fix_agencies_specialists_db_column'),
        ('accounts', '0061_fix_agencies_pk_v2'),
    ]

    operations = [
    ]
